### ISSUE TITLE
Cope with BMC Admin access

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/bmc-catcher#13]
By introduction of the super user in https://github.com/metal-stack/go-hal/pull/7 we introduced the possibility that machines either have the default ADMIN user or the metal `root` user to access the BMC.

We should decide based on the configuration of the metal-api which one to use.

**Comment by majst01** [comment]
We could also create the root user and give the bmc-catcher the supermetal password with the deployment.

**Comment by Gerrit91** [comment]
I think this can be closed because we have #40. Please re-open if necessary.
