### ISSUE TITLE
Current dhcp lease not updated in metal-api sometimes

### ISSUE THREAD

**Issue by muhittink** [metal-stack/bmc-catcher#3]
It seems to be, that there is an issue with updating the current lease in metal-api:

`metalctl machine ipmi | grep 00000000-0000-0000-0000-XXXXXXXXX`

`00000000-0000-0000-0000-XXXXXXXXX	  	192.168.2.224:623	aa:bb:cc:dd:ee:ff	X11SDV-8C-TP8F   	1.2         	1.71       	s2-xlarge-x86`

Also the BMC firmware of a storage node can't be `1.71`.  Current is `1.31`

If you track the mac on both dhcp servers you will see, that the old lease is current in metal-api:

`user@mgmtsrv02:~$ dhcp-lease-list --all |grep aa:bb:cc:dd:ee:ff`

`aa:bb:cc:dd:ee:ff   192.168.2.224   -NA-           2020-04-16 14:22:09 -NA-  `

`user@mgmtsrv01:~$ dhcp-lease-list |grep aa:bb:cc:dd:ee:ff
aa:bb:cc:dd:ee:ff  192.168.2.106   -NA-           2020-04-17 07:45:36 -NA-`

The newer lease is accessible and works as usual.

**Comment by Gerrit91** [comment]
Could be resolved by #7. Please confirm this issue still exists in test.

**Comment by majst01** [comment]
can we close this ?

**Comment by Gerrit91** [comment]
Pretty old one, no complains for a long time, closing.
